name: CI
on: [push]
jobs:
  eslint:
    name: Lint codebase
    runs-on: ubuntu-latest

    steps:
      - name: Ceckout codebase
        uses: actions/checkout@v2

      - name: Install packages
        run: npm i
      - name: Run eslint
        run: npm run lint
